---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: user-management-system
          image: khushpreet/user_management_system  
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flaskapi-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: main
  type: LoadBalancer
