name: Build and push docker image
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out to main repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build image
      run:  docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
    - name: push image
      run:  docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
      
    - name: Check out to repository user-management
      uses: actions/checkout@v2      
      with:
        repository: khushpreet98/user-management
        token: ${{ secrets.token }}
     #   ref: master

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: yq -i  eval '.images.repository= "${{ secrets.DOCKER_USERNAME }}/user_management_system:${{ github.sha }}"' values.yaml
      
    - name: Commit files
      run: |
        git config user.email "khushpreet@wanclouds.net"
        git config user.name "khushpreet98"
        git commit -am "update image tag with latest commit id"
        git push origin master
