name: Build and push docker image
on: [ push ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out to main repository
      uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build image
      run:  docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}
    - name: push image
      run:  docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}
      
        
  deploy: 
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Check out to repository user-management
      uses: actions/checkout@v2      
      with:
        repository: khushpreet98/user-management
        token: ${{ secrets.token }}
        ref: master
    - name: update k8s resources
      run: yq -i  eval '.images.repository= "${{ secrets.DOCKER_USERNAME }}/user_management_system:${{ steps.vars.outputs.sha_short }}"' values.yaml

  test-deploy:
    if: github.ref == 'refs/heads/Dockerfile'
    runs-on: ubuntu-latest
    steps:
    - name: update k8s resources
      run: yq -i  eval '.images.repository= "${{ secrets.DOCKER_USERNAME }}/user_management_system:${{ steps.vars.outputs.sha_short }}"' values-test.yaml
      
    - name: Commit files
      run: |
        git config user.email "khushpreet@wanclouds.net"
        git config user.name "khushpreet98"
        git commit -am "update image tag with latest commit id"
        git push origin master
      
