name: Docker Image CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/user_management_system:${{ github.sha }}
    - name: push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/user_management_system:${{ github.sha }}
