name: Build and push docker image
on: [ push ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
 #   env:
 #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - name: Check out to main repository
      uses: actions/checkout@v2
      
    - name: Get the short commit id
      id: image-tag
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
    - name: Get the branch name
      run: |
        echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
        echo "branch is" $BRANCH_NAME

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build image
      run:  docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.BRANCH_NAME }}-${{ steps.image-tag.outputs.sha_short }}
    - name: push image
      run:  docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.BRANCH_NAME }}-${{ steps.image-tag.outputs.sha_short }}
             
    - name: Check out to repository user-management
      uses: actions/checkout@v2      
      with:
        repository: khushpreet98/user-management
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: master
        
    - name: update helm manifest in values.yaml
      if: github.ref == 'refs/heads/master'
      run: yq -i  eval '.images.repository= "${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.BRANCH_NAME }}-${{ steps.image-tag.outputs.sha_short }}"' values.yaml

    - name: update helm manifest in values-test.yaml
      if: github.ref == 'refs/heads/added/jenkinsfile'
      run: yq -i  eval '.images.repository= "${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.BRANCH_NAME }}-${{ steps.image-tag.outputs.sha_short }}"' values-test.yaml
            
    - name: Commit files
      run: |
        git config user.email "khushpreet@wanclouds.net"
        git config user.name "khushpreet98"
        git commit -am "update image tag with latest commit id ${{ env.BRANCH_NAME }}-${{ steps.image-tag.outputs.sha_short }}"
        git push origin master
        
   # - name: Notify workflows status to Slack
    #  uses: 8398a7/action-slack@v3
     # with:
      #  status: ${{ job.status }}
       # fields: repo,message,commit,author,eventName,ref,workflow,job,took
        #channel: '#github-workflows'
      #if: always()
