name: Build and Push Docker Image and deploy for vpcplus-aws-be
on:
  push:
    branches: [ ci-github-actions ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}
        docker build -t ${{ secrets.DOCKERHUB_REPOSITORY_1 }}:${{ steps.vars.outputs.sha_short }} -f aws/discovery/Dockerfile . 
    - name: push image
      run:|  
        docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}
        docker push ${{ secrets.DOCKERHUB_REPOSITORY_1 }}:${{ steps.vars.outputs.sha_short }}

    - name: Check out to repository vpc-microservice-deployment
      uses: actions/checkout@v2      
      with:
        repository: Wanclouds/vpc-microservice-deployment
        token: ${{ secrets.token }}
        ref: test-gitactions

    - name: Update helm manifest of draas instance values.yaml
      if: github.ref == 'refs/heads/main'
      run:|
        yq -i  eval '.images.awsdraasimagetag= "${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}"' deployment_kubernetes/manifests/backend/helm/aws-vpc/values.yaml
        yq -i  eval '.images.awsbackenddiscoverytag= "${{ secrets.DOCKERHUB_REPOSITORY_1 }}:${{ steps.vars.outputs.sha_short }}"' deployment_kubernetes/manifests/backend/helm/aws-vpc/values.yaml

    - name: Update helm manifest of aws-vpc instance aws-values.yaml
      if: github.ref == 'refs/heads/wip-ibm-draas-test'
      run: |
        yq -i  eval '.images.awsdraasimagetag= "${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}"' deployment_kubernetes/manifests/backend/helm/aws-vpc/values-ibm-marketplace.yaml
        yq -i  eval '.images.awsbackenddiscoverytag= "${{ secrets.DOCKERHUB_REPOSITORY_1 }}:${{ steps.vars.outputs.sha_short }}"' deployment_kubernetes/manifests/backend/helm/aws-vpc/values-ibm-marketplace.yaml

    - name: Update helm manifest of draas-stage instance values-draas-stage.yaml
      if: github.ref == 'refs/heads/develop'
      run:|
        yq -i  eval '.images.awsdraasimagetag= "${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}"' deployment_kubernetes/manifests/backend/helm/aws-vpc/values-draas-stage.yaml
        yq -i  eval '.images.awsbackenddiscoverytag= "${{ secrets.DOCKERHUB_REPOSITORY_1 }}:${{ steps.vars.outputs.sha_short }}"' deployment_kubernetes/manifests/backend/helm/aws-vpc/values-draas-stage.yaml

    - name: Update helm manifest of testing instance 
      if: github.ref == 'refs/heads/ci-github-actions'
      run:|
        yq -i  eval '.images.awsdraasimagetag= "${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}"' deployment_kubernetes/manifests/backend/helm/aws-vpc/values.yaml
        yq -i  eval '.images.awsbackenddiscoverytag= "${{ secrets.DOCKERHUB_REPOSITORY_1 }}:${{ steps.vars.outputs.sha_short }}"' deployment_kubernetes/manifests/backend/helm/aws-vpc/values.yaml

    - name: Commit files
      run: |
        git config user.email "khushpreet@wanclouds.net"
        git config user.name "khushpreet98"
        git commit -am "update image tag with latest commit id"
        git push origin test-gitactions
